apiVersion: v1
kind: Service
metadata:
  name: virt-asst-service
  labels:
    app: virt-asst
spec:
  type: NodePort
  selector:
    app: virt-asst
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
